services:
  samba:
    container_name: samba
    image: crazymax/samba
    privileged: true
    ports:
      - 445:445
      - 3702:3702
      - 5355:5355
    volumes:
      - ${CONFIGURATION_PATH}/samba/data:/data
      - ${EXT_DRIVE_PATH}:/samba/public
    environment:
      - TZ=${TZ}
      - SAMBA_HOSTS_ALLOW=${SAMBA_HOSTS_ALLOW}
    restart: always
