services:
  app:
    container_name: lovelace-kindle-screensaver
    image: sibbl/hass-lovelace-kindle-screensaver:latest
    restart: unless-stopped
    environment:
      - HA_BASE_URL=http://${SERVER_IP}:8123
      - HA_SCREENSHOT_URL=/dashboard-devices/nook?kiosk
      - HA_ACCESS_TOKEN=${HA_ACCESS_TOKEN}
      - CRON_JOB=*/10 * * * *
      - RENDERING_SCREEN_HEIGHT=800
      - RENDERING_SCREEN_WIDTH=600
      - GRAYSCALE_DEPTH=8
      - OUTPUT_PATH=/output/cover.png
      - LANGUAGE=en
      - ROTATION=${ROTATION}
      - TZ=${TZ}
    ports:
      - 5000:5000
    volumes:
      - ${CONFIGURATION_PATH}/lovelace-screensaver/:/output
