services:
  app:
    container_name: joplin
    image: florider89/joplin-server:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "22300:22300"
    environment:
      - APP_BASE_URL=https://joplin.freekode.org
      - APP_PORT=22300
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DB_CLIENT=pg
  db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - ${CONFIGURATION_PATH}/joplin/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
