services:
  app:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: 1000:1000
    ports:
      - '2001:80'
    volumes:
      - ${EXT_DRIVE_PATH}:/srv
      - ${CONFIGURATION_PATH}/filebrowser/database.db:/database.db
      - ${CONFIGURATION_PATH}/filebrowser/.filebrowser.json:/.filebrowser.json
