services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ${CONFIGURATION_PATH}/redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ${CONFIGURATION_PATH}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ${CONFIGURATION_PATH}/data:/usr/src/paperless/data
      - ${CONFIGURATION_PATH}/media:/usr/src/paperless/media
      - ${CONFIGURATION_PATH}/export:/usr/src/paperless/export
      - ${CONFIGURATION_PATH}/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
