version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    privileged: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${CONFIGURATION_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${CONFIGURATION_PATH}/nginx/snippets:/etc/nginx/snippets
      - ${CONFIGURATION_PATH}/nginx/keys:/etc/nginx/keys
      - ${CONFIGURATION_PATH}/nginx/cdn:/srv/cdn
