services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '1899:8080'
    volumes:
      - ${CONFIGURATION_PATH}/stirling-pdf/trainingData:/usr/share/tessdata
      - ${CONFIGURATION_PATH}/stirling-pdf/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=${LANGS}
