services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '1899:8080'
    volumes:
      - ${CONFIGURATION_PATH}/stirling-pdf/trainingData:/usr/share/tessdata
      - ${CONFIGURATION_PATH}/stirling-pdf/extraConfigs:/configs
    env_file: .env
