services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 51820:51820/udp
    volumes:
      - ${CONFIGURATION_PATH}/wireguard/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PEERS=${WIREGUARD_PEERS}
